### ISSUE TITLE
choco-cleaner - deleting cache files (problem with nonascii paths)

### ISSUE THREAD

**Issue by 07pepa** [bcurran3/ChocolateyPackages_CCR#106]
There is most likely bug

steps to reproduce
* have up to date win 10
* set %TMP% enviroment variable to path containing non ascii chars (like: ěščřžýáíéúů especialy ť ň and their uppercase variants etc)
* enable chashe file cleaning
* run choco-cleaner

It should fail at  row:55 .... for some stupid reason path become malformed ... and yes i cheched it  and path is there and can be deleted even tmp is set.... so some stupid powershell bug (or settings is required)

i can provide transcript and exact enviroment variables/settings via mail (will not provide publicly for obvious reasosn) if reproduction steps are not concrete enought

**Comment by bcurran3** [comment]
Line 55 is different between versions. I need the actual error message.

**Comment by bcurran3** [comment]
Line 55 in the current version (0.5.2) shows as:
`Remove-Item -path $env:tmp\chocolatey -recurse -ErrorAction SilentlyContinue`
..which I'm guessing is correct line you're referencing.

It's standard stuff and I'm guessing it's a PowerShell issue. I can probably parse $env:tmp/%tmp% first but I'll have to figure out what to look for or maybe what to not look for.

Try this for me: Put "'s around $env:tmp\chocolatey ("$env:tmp\chocolatey") and see if that makes a difference. Let me know. It would be nice if the fix was that easy.

**Comment by 07pepa** [comment]
yes the line you referenced  is "incorect" somehow ... and sory it took me time to get around

there is log

  **  Deleting unnecessary Chocolatey _processed.txt (WTF?) file...
  **  Deleting unnecessary Chocolatey .ignore files...
  **  Deleting unnecessary Chocolatey .old files...
  **  Deleting unnecessary Chocolatey cache files...
Remove-Item : An object at the specified path C:\Users\TAKA~1 does not exist.
At C:\ProgramData\chocolatey\bin\choco-cleaner.ps1:55 char:6
+      Remove-Item -path $env:tmp\chocolatey -recurse -ErrorAction Sile ...
+      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-Item], PSArgumentException
    + FullyQualifiedErrorId : Argument,Microsoft.PowerShell.Commands.RemoveItemCommand

  **  Deleting unnecessary Chocolatey config backup files...
  **  Deleting unnecessary Chocolatey lib-bad package files...
  **  Deleting unnecessary Chocolatey lib-bkp package files...
  **  Deleting unnecessary Chocolatey extracted file logs...
  **  Deleting unnecessary Chocolatey log files...
  **  Deleting unnecessary Chocolatey package embedded archive files in toolsDir...
  **  Deleting unnecessary Chocolatey package embedded archives and executables in .nupkg files...
  **  Deleting unnecessary Chocolatey package embedded license files...
  **  Deleting unnecessary Chocolatey package embedded Microsoft installers...
  **  Deleting unnecessary Chocolatey package embedded various read me files...
  **  Deleting unnecessary Nuget cache files...


as you can see it thinks the path is C:\Users\TAKA~1


but actual path specified in env vars is %USERPROFILE%\AppData\Local\Temp  ... that yeld C:\Users\Taťka\AppData\Local\Temp  .... so windows sucks... at chars as (ěščřžýáíéúůďťň)

trying "'s around $env:tmp\chocolatey" do not fix it

Remove-Item : An object at the specified path C:\Users\TAKA~1 does not exist.
At C:\ProgramData\chocolatey\bin\choco-cleaner.ps1:55 char:6
+      Remove-Item -path "$env:tmp\chocolatey" -recurse -ErrorAction Si ...
+      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-Item], PSArgumentException
    + FullyQualifiedErrorId : Argument,Microsoft.PowerShell.Commands.RemoveItemCommand

  **  Deleting unnecessary Chocolatey cache files...
Remove-Item : An object at the specified path C:\Users\TAKA~1 does not exist.
At C:\ProgramData\chocolatey\bin\choco-cleaner.ps1:55 char:6
+      Remove-Item -path ("$env:tmp\chocolatey") -recurse -ErrorAction  ...
+      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-Item], PSArgumentException
    + FullyQualifiedErrorId : Argument,Microsoft.PowerShell.Commands.RemoveItemCommand

**Comment by bcurran3** [comment]
I'm not sure yet if this is just a "PowerShell thing" or if there are some issues with your environmental variables. I say this because you mention "%USERPROFILE%\AppData\Local\Temp" and I'm not sure why.

Make sure $env:tmp/%tmp% and $env:userprofile/%userprofile% are correct and different please. TMP should lead you to c:\users\username\appdata\local\temp and USERPROFILE should lead you to c:\users\username.

If the variables are set correctly, post their settings please as I'd like to see the weird characters and maybe I'll do some testing with the same or similar account name in sometime in the future.

**Comment by 07pepa** [comment]
i mentioned a %USERPROFILE%\AppData\Local\Temp  since it is setting of my TMP variable ( and it is default clean install of win 10 )
and yes i checked  that that path in TMP env and it lead to existing directory .... with chocolatey folder in it everything checks out but it does not work

so it is a stupid powershell thing then...  maybe *.bat script would not fail.... i personaly would do it in python but i have feeling that it is no option

since this is not problem of your software but powershell... i am closing this issue
