### ISSUE TITLE
Modifying choco-package-list-backup.xml

### ISSUE THREAD

**Issue by jeff9315** [bcurran3/ChocolateyPackages_CCR#110]
I was trying to modify the options in the XML file. I first tried all my custom locations but none of those worked. Then I tried changing the XML file in the Chocolatey bin directory but that doesn't work because I don't have permissions. What's the correct way to modify the XML file? 

And maybe in order to help the next person, there should be a Readme file that gets copied to all the custom locations (incl Google Drive, OneDrive, etc) that documents the process.

BTW ... I really LOVE your various tools even though I'm brand new to Chocolatey! Thanks.

**Comment by bcurran3** [comment]
Hi Jeff.

The only place to effectively edit the config is C:\ProgramData\chocolatey\bin\choco-package-list-backup.xml; all others are backups of it.

If you're trying to edit the XML file with the same account that installed choco-package-list-backup, you should be able to. Either way, you can edit it if you're an administrator. You can use Notepad++ which has a feature to re-run and load a file as admin. You can also run Command Prompt as admin, switch to the directory with the XML and then run notepad choco-package-list-backup.xml and it will  work.

I'm not really sure what there is to document in a readme. Everything's pretty well documented on the Chocolatey package page, in the script, and in the XML file. Let me know what you think might be able to be documented more or better.

**Comment by jeff9315** [comment]
Hi Bill ... I am an administrator and didn't have access to the account it was installed in. I wasn't able to edit anything in C:\ProgramData no matter what I tried. So, this is what I put into the XML file as a comment to remind me. This is what I think might need to be documented ...

```
To change this file (choco-package-list-backup.xml):
	You MUST change it in C:\ProgramData\chocolatey\lib\choco-package-list-backup\tools
        All other places are just copies of this one and are not used.
	But you MUST be owner to change anything in C:\ProgramData
	If you are NOT owner, you'll need to uninstall it and reinstall it while in the correct account. 
	Or maybe you can just reinstall it using the force parameter. Not sure about that.

```

**Comment by bcurran3** [comment]
Jeff,

 C:\ProgramData\chocolatey\lib\choco-package-list-backup\tools is NOT the path I mentioned previously, you should NOT find a copy of choco-package-list-backup.xml there. It's unpackaged there during choco-package-list-backup's install, but then moved to C:\ProgramData\chocolatey\bin on new installs and deleted on updates as not to overwrite your configuration changes.

Everything in C:\ProgramData requires administrative privileges. This is default Windows security because data stored there is global for programs relevant to all users. (As apposed to C:\users\USERNAME\AppData which is for program data relevant to only that one user, USERNAME.)

The installing user of choco-package-list-backup gets full control, modify, read & execute, read, and write privileges to C:\ProgramData\chocolatey\bin\choco-package-list-backup.xml. If you're not the installing user, all local Administrators have the same privileges. 

If you ARE in the local administrators group then you should have no problems, BUT programs, i.e. Command Prompt or your favorite text editor, might still need to be "Run as administrator." If you do not do this, you will probably not have administrative privileges on the files.

Alternatively you can just browse to C:\ProgramData\chocolatey\bin\choco-package-list-backup.xml and edit it's security properties to add in your account with full control or modify privileges. 

I'm confident you can do this.

SIDENOTE: For those times when you're in the Command Prompt and can't do something because you forgot to run as administrator... I love this little tool: https://chocolatey.org/packages/elevate as I can just type "el" and get a new command prompt at the same path location with administrative privileges. Try it, you might like it.
