### ISSUE TITLE
Automatically updating packages

### ISSUE THREAD

**Issue by devedse** [bcurran3/ChocolateyPackages_CCR#116]
Hi bcurran3,

A quick question I have in regards to maintaining Chocolatey packages (which you're obviously an expert on :smile:)

I've been made a maintainer for a chocolatey package for a tool I often use:
https://chocolatey.org/packages/FileOptimizer

What I'd like to do though is that once the original maintainer releases a new version, it automatically uplaods a new package with checksum on the Chocolatey package manager.

So basically my question(s)
1. How do you do updates of packages, you do this automatically? Or do you subscribe to new versions being puslished by tools and update them once you see them? Or do you like manually check all 400 tools every day?
2. FileOptimizerFull get's published on SourceForge. I couldn't really find a way to trigger some kind of script that fires once a new version gets published. Do you have any ideas on this? (Or what would you suggest in maintaining this package?)

**Comment by bcurran3** [comment]
Hi @devedse thanks for the unneeded compliments, I'd be willing to answer your questions without them. :)

Believe it or not, I actually do all my packages manually. It's foolish and I need to convert to automation. The defacto way to automate creation and pushing of new packages is AU:
https://chocolatey.org/packages/au

I've been planning to start using AU for a long time. There are hurdles. The foremost simply being I haven't spent the time to go through it completely and figure out how it works. At a high level you create an update.ps1 script that will basically have to scrape the info from the SourceForge page and then make determinations based on that info. So doing that is going to be highly reliant on you determining changes to the webpage (a new version of the program) and how to deal with it. There are tutorials up on YouTube if you search and there are plenty of examples in the package repositories of many Chocolatey maintainers. If you can find one that similarly updates via scraping SourceForge you're going to be 90% done.

Good luck!

...and help me when you've got it all figured out! LOL!

Honestly I feel pretty stupid for not utilizing AU yet. I've got less free time the last few months and it basically gets used updating the packages where updating the updating of packages would be more self serving (time saving!) in the long run. From what I've seen, in a lot of cases, it's harder to write an update.ps1 then it is to copy and paste a new checksum into a package. But that's a very limited view as time goes by - I need to get my but working on those AU scripts!

**Comment by devedse** [comment]
@bcurran3 , thanks for the explanation. One more quick question:

Those update.ps1 scripts, will they be ran by chocolatey internally? Or do you still have to run them manually and then once complete, push the updated package to the chocolatey repository?

**Comment by bcurran3** [comment]
Chocolatey doesn't know anything about them.

You have to run them manually or automate them yourself. I'm not sure but I think people automated it somehow using AppVeyor. I could be wrong and could be WAY wrong as I haven't done this. Since I haven't "converted" to doing this yet, I'm really the wrong guy to ask.

I think you should hit up some of the guys who are updating packages this way and get real and detailed info from them. I'd be interested in learning more about this too.

Just SOME of the places you could start looking at or ask advice:
https://github.com/majkinetor/au-packages
https://github.com/chocolatey-community/chocolatey-coreteampackages

dtgm disappeared about two years ago from the Chocolatey community, yet some of his packages continue to be automatically updated!:
https://github.com/dtgm/chocolatey-packages

Believe me, I'm the wrong source for this subject as I'm only about 1/12 of a foot ahead of you and you're gaining traction fast. :)
