### ISSUE TITLE
choco-cleaner: running manually

### ISSUE THREAD

**Issue by ghost** [bcurran3/ChocolateyPackages_CCR#125]
https://chocolatey.org/packages/choco-cleaner

I see that you've moved to the `choco://` protocol support and the description has been updated. Some may prefer not to install this unofficial package and are fine with running choco-cleaner manually — if possible, can you add instructions to the description?

**Comment by bcurran3** [comment]
Truthfully, I'm lost on this request. Please clarify.

> I see that you've moved to the choco:// protocol support and the description has been updated.

I created the choco:// protocol. Every thing I have packaged since then supports it.

> Some may prefer not to install this unofficial package and are fine with running choco-cleaner manually

If you are talking about choco:// protocol support - no one needs to install it if they don't want to. If you're talking about choco-cleaner you can't run it if you don't install it. 

Either one you may be talking about... both are unofficial.

> — if possible, can you add instructions to the description?

Both packages have, IMHO, good instructions. What do you believe is lacking?

**Comment by ghost** [comment]
> I created the choco:// protocol. Every thing I have packaged since then supports it.
> 
Sorry, I missed this.
> If you are talking about choco:// protocol support - no one needs to install it if they don't want to. If you're talking about choco-cleaner you can't run it if you don't install it.

I see. What I intended to ask was how to execute choco-cleaner manually (in Powershell), which has been possible in the past. I wanted to inspect how much space I save.

**Comment by bcurran3** [comment]
Just type choco-cleaner from PowerShell, it's in the path and will run.

Next release will work from Command Prompt as well!
