### ISSUE TITLE
choco-nuspec-checker: returning with exitcode/stderr would be helpful

### ISSUE THREAD

**Issue by BananaAcid** [bcurran3/ChocolateyPackages_CCR#136]
Having exitcodes/errorlevels returned would be helpful in scripts and any other tools (automation).

As well as having the errors and warnings echoed out to stderr.

**Comment by bcurran3** [comment]
Agreed.
You're the first to provide ANY kind of feedback on CNC. 
There are a few small features I'd like to get added first and then make it work recursively. I'll try to sneak in some error handling along the way when possible.
You're welcome to help make it better!

**Comment by BananaAcid** [comment]
About writing to stderr, this might be helpful: [how-do-i-write-to-standard-error-in-powershell](https://stackoverflow.com/a/15669365/1644202) since cmd.exe and powershell.exe behave differently.

**Comment by bcurran3** [comment]
@BananaAcid I hope you haven't been holding your breath. :-)

New release today with exit codes:
* 2023.05.17 - CNC now returns a non-zero exit code if there are any required changes and displays the total required changes of all nuspec files when the -Recurse switch is used

I don't think I'm going to move ahead with changing the displayed output, BUT I do plan to soon add logging of errors in the same way I've updated choco-update-all and choco-cleaner to do. 

A little more on my reasoning: CNC was designed for maintainers to run manually after updating a package and to give them an opportunity to fix problems before they push their updated package; i.e. faster fix response. I can definitely imagine how CNC could be used in automation. I would expect that any automation scripts would not push the package on an error and hold the package for a local review... and that can now be done. I can also imagine that with a LOT of work in that automation script it might even be possible to fix the errors and then continue to push the package but I find that highly highly unlikely due to the complexity. With that said, if CNC is used in automation and an error code 1 is ignored by the automation script and the package is still pushed... the validator is going to e-mail out the problem to you fairly soon and you'll most likely have that e-mail when you wake up and read it before viewing any automation error logs. (This is all assuming using the CCR of course. I have no idea what enterprises are using my script as I get no feedback or sponsorship, nor do I know their workflow; i.e. if their server does validation/verification testing of packages.) SO... I feel logging errors seems to be an appropriate solution.

If you feel strongly on having the overall output re-written feel free to re-open this issue or do a PR.
