### ISSUE TITLE
choco-protocol-support: add version param

### ISSUE THREAD

**Issue by BananaAcid** [bcurran3/ChocolateyPackages_CCR#138]
since there is `choco install packagename --version 1.0`, it would be great, if `choco://packagename?version=1.0` would work. 

And possibly whatever params are appended, be translated as well.

**Comment by bcurran3** [comment]
Hi Nabil. AFAIK, I'm the only one in the world that publishes choco protocol links. :)
Though the suggestion is interesting and probably not hard to implement, I'm not sure it's worth putting my effort into something that nobody, to my knowledge, would use.

Do you have a specific use case in mind? I could see where this would be advantageous in a corporate environment, but again, I have no knowledge of it actually be used outside the description on packages I maintain.

**Comment by BananaAcid** [comment]
hi. well have a look at [that](https://chrome.google.com/webstore/detail/chocolatey-appstore/gkehnkphfligaeniienfamgdfocegffl) and [this - there might be version spiced links for install - currently stripped out](https://chocolatey.org/packages/chocolatey-appstore-chrome/1.0.0) 

Since protocol links work with all packages, I was introducing it in a corporate setting. Several years ago, I was coding a .NET tool handling several ssh:,winscp:,etc protocols for an intranet thing - this package got me the moment I saw it

**Comment by bcurran3** [comment]
Cool. I'll install it and play with it soon as I have time.

Ahhh. Yes. I smelled a corporate purpose. I was just waiting to have it fished out. :)

I'll see about updating it when time permits. I'll be honest, I'm busy as hell right now. For corporate use, donations/work for hire can bump up the priority. :)

My plan will be to make the next version an .EXE "assembly." It was that way originally (https://chocolatey.org/packages/chocoprotocolstub) but I got blow-back and was told that Rob "doesn't want chocolatey.org to be the first validation in the "web of trust" for assemblies that are placed onto chocolatey.org. Rather, that this validation is asserted elsewhere." 

What I didn't understand at the time was that I just needed to publish the .EXE elsewhere; i.e. a product page... wish they could have worded the reasoning differently or suggested how to fix the "problem." I'll officially put it up the next version on my business site on a product page so that it is "validated" elsewhere. Ran into the same problem with InstChoco but figured out what they wanted and walah! REF: http://lacomputerbuddy.com/InstChoco/ (You should look at this if you haven't already.)

**Comment by BananaAcid** [comment]
Good to know :)

**Comment by DJCrashdummy** [comment]
adding `package-parameters=` and `install-arguments=` would be awesome! :heart_eyes:

**Comment by bcurran3** [comment]
@BananaAcid - Done! In beta... 

New pre-release proof of concept out:
choco install choco-protocol-support --version=0.0.2.0-pre1 --pre 

@DJCrashdummy - In the works. The parsing might be a real PITA. We'll see, I've got the basics in it.

Please try and report back.

**Comment by bcurran3** [comment]
I did a few more enhancements and it's ready for release as v.0.2

choco install choco-protocol-support --version=0.2
