### ISSUE TITLE
(choco-cleaner) Breaks Keypirinha by deleting lib.zip / config variables always true

### ISSUE THREAD

**Issue by tordenflesk** [bcurran3/ChocolateyPackages_CCR#140]
see this:
https://github.com/Keypirinha/Keypirinha/issues/404#issuecomment-566287554

**Comment by bcurran3** [comment]
Comment left there. 

Just need to tell choc-cleaner to NOT delete archive files in the choco-cleaner.xml file.

**Comment by maykot** [comment]
I don't know if it's just my computer, but it seems that the settings in the xml files are just being ignored by the script. The script still deletes zip files even if I change the value of the DeleteArchives field to false.

After some quick testing and googling I figured out that this is happening because the script is importing the values as strings and PowerShell will evaluate any non-zero length string in an if statement to true.

This is consistent with the fact that deleting the field value altogether has the same effect of setting the corresponding variable to false. So I'm using this workaround for now.

Can you confirm that this is indeed what is happening? I.e., that this isn't just a weird bug specific to my system.

**Comment by tordenflesk** [comment]
I set:

`<DeleteArchives>false</DeleteArchives>`

and lib.zip survives just fine.

Windows 7, PS 5.1.14409.1018

**Comment by maykot** [comment]
That is weird. Windows 10 1909, PS 5.1.18362.145 here.

**Comment by bcurran3** [comment]
The script reads in the XML file and sets the variable $DeleteArchives as whatever string it finds, which should be set as "true" or "false." The value is the string and not boolean $true or $false. 

Looking at the code now
```
if ($DeleteArchives)
    {	
     Write-Host "  **  Deleting unnecessary Chocolatey package embedded archive files in toolsDir..." -ForeGround Green
     Remove-Item -path $env:ChocolateyInstall\* -recurse -include *.zip,*.rar,*.7z,*.gz,*.tar,*.sfx,*.iso,*.img,*.msi,*.msu,*.msp -ErrorAction SilentlyContinue
	}
```
@maykot You're 100% correct. I effed up. I'm not checking the variables correctly. This is a long standing bug. Thank you for finding it. I'll fix it as soon as I can. Please run with the kludge of leaving the value blank to set as false.

@tordenflesk I'm glad it worked for you, but if I'm looking at it correctly right now, it shouldn't have worked!

**Comment by maykot** [comment]
Hahaha, no problem @bcurran3, happy to help!

I also don't understand how it worked for @tordenflesk. The only thing I can think of is that maybe the file was open while the script was running.

**Comment by bcurran3** [comment]
When you get a chance, please try this. Should work:
https://chocolatey.org/packages/choco-cleaner/0.0.6

cinst choco-cleaner --version 0.0.6 until it gets through moderation.

**Comment by maykot** [comment]
Yep, works perfectly now. Thanks for the fix!

**Comment by bcurran3** [comment]
![image](https://user-images.githubusercontent.com/14026600/71110714-ae2bf880-217c-11ea-95fd-d5f695e5da72.png)
