### ISSUE TITLE
AngryIP depend on a openJDK JRE rather then Oracle JRE

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [bcurran3/ChocolateyPackages_CCR#142]
Due to Oracle licensing changes prohibiting business use.

I would suggest switching the AngryIP java dependency to an AdoptOpenJDK build, probably this one- https://chocolatey.org/packages/adoptopenjdk8jre

**Comment by bcurran3** [comment]
IMHO most of the world uses's Oracle's (Sun's!) version of JAVA. I don't really like the idea of switching away from it unless I see (proof?) of the trend changing.

**Comment by TheCakeIsNaOH** [comment]
The chocolatey core team has moved to OpenJDK 
https://github.com/chocolatey-community/chocolatey-coreteampackages/issues/1315

The other package that I know about that depends on Java has switched to AdoptOpenJDK-
https://github.com/wjk/BFG-Windows/issues/3

**Comment by ctminime** [comment]
> 
> 
> IMHO most of the world uses's Oracle's (Sun's!) version of JAVA. I don't really like the idea of switching away from it unless I see (proof?) of the trend changing.

Seriously? Every company that I know of is moving away from Oracle Java. Even the default Java package for Redhat, Debian, and Arch based distros have moved away from Oracle Java (see references below). Even running JUST the Oracle JRE within a business requires you to pay for it (Oracle Java's licensing link below clearly states that the JRE is free for personal use but not bussiness).

So, IMHO those 3 distros (which are the parents of most other distros) moving away from Oracle Java is proof of a trend change.

https://wiki.debian.org/Java

https://access.redhat.com/documentation/en-us/jboss_enterprise_application_platform/6/html/administration_and_configuration_guide/configure_the_default_jdk_on_red_hat_enterprise_linux

https://wiki.archlinux.org/index.php/Java

https://www.oracle.com/technetwork/java/javase/overview/oracle-jdk-faqs.html

**Comment by bcurran3** [comment]
@TheCakeIsNaOH 

They had a discussion about it, but from what I read they have no packages with a Java dependency.

@ctminime 

Seriously!

I'm not catering to companies, I'm catering to normal Chocolatey FOSS users. If you're working for a company using Chocolatey, you should be using Chocolatey 4 Business. If you're working for a company with an IT department you should be using Chocolatey 4 Business and the IT department should be using company created packages (with whatever Java dependency you prefer.)

I completely understand your point of view, and the reasons related to Oracle's new licensing. I just see the package for Joe Average. OK, I'll admit that Joe Average probably has no need for AngryIP though.

Oracle's Java is still the defacto standard; anything else is an alternate/substitution. They, via proxy by buying Sun ("The network is the computer."), invented it.

With that said I have a number of packages that require Java and have it as a dependency. It will take time and effort to refactor something that already works using the standard to test and see if it will work with an alternative version. This is not about one package, this is about testing all the programs that I personally use that require Java and see if they will transition and still work. This is not just about this package. ATM I don' t know if I can have dual versions of Java installed and no conflicts. It's not about switching one package, it's about ultimately switching at least a dozen packages including a few that are in no longer development.

Honestly I'm more inclined to drop the dependency altogether and just make a disclaimer that you need some form of Java installed. I guess I could have the script check for the various Java packages and display some message if nothing is found. Needs some thinking. If all the various vendor versions of Java are compatible and interchangeable, what would be really nice is a meta package that lists all of them and if you have any one of them installed, it passes. I don't think Chocolatey has the built-in OR logic for it though...

Since this has been open for awhile and I'm in no rush to change what works ("If it ain't broke, don't fix it."), I'm going to record a statistical snapshot in time to help watch the "trend" to see about making a more informed decision at a future date. This seems to me to be a fair way to do this. At the moment the vote to change the Java dependency is 2 with 3,479 abstain.

![image](https://user-images.githubusercontent.com/14026600/87779316-77d15d00-c7e1-11ea-88e8-cd021bf8f25a.png)

![image](https://user-images.githubusercontent.com/14026600/87779391-920b3b00-c7e1-11ea-99f3-53918ef7a4a2.png)


We can now use those download stats as a historical record from today and compare them to the stats in a month, two, three, six, a year or such and see what is trending. As of today it's basically 15 million to 74 thousand, but that's not fair since Oracle's license changed towards the end of 2019. So let's watch and see what happens.

**Comment by TheCakeIsNaOH** [comment]
As a compromise, how about using the Oracle OpenJDK? It is still Oracle Java, but it is a build licensed under GPLv2 rather than their other EULA that prohibits business use without payment. 
https://chocolatey.org/packages/openjdk8jre

**Comment by TheCakeIsNaOH** [comment]
> Honestly I'm more inclined to drop the dependency altogether and just make a disclaimer that you need some form of Java installed. 

Given that there has been no movement on https://github.com/chocolatey/choco/issues/858, and given the number of backloged items that would need to be dealt with first, I'm kind of leaning toward this option these days.

The install script could do a `Get-Command java.exe`, and if java is not on the path, then print out a big, red(or yellow), warning that java needs to be installed manually.  I'm doing something similar with `javac.exe` to check for a java compiler in the maven package: https://github.com/TheCakeIsNaOH/chocolatey-packages/blob/master/maven/tools/chocolateyinstall.ps1#L22-L24

I REALLY want `provides` to be implemented in the `.nuspec`, working around it's absence for java is getting annoying.

**Comment by bcurran3** [comment]
From 3.8.2 release notes:
`* Windows installer now includes a stripped-down JRE to avoid downloading Java separately`

This has been decided for us by the dev; as of v 3.8.2 a JRE (Liberica?) is included in the installer by default. Problem solved externally.

**Comment by TheCakeIsNaOH** [comment]
@bcurran3 thanks for keeping up to date with it.
