### ISSUE TITLE
Outdated Instruction ... minor correction

### ISSUE THREAD

**Issue by jeff9315** [bcurran3/ChocolateyPackages_CCR#164]
I just noticed that the first Instructions on GitHub say:
`Edit \ProgramData\chocolatey\bin\choco-package-list-backup.xml to customize your backup(s). It's easy, there are comments.`
I think that probably is outdated and should reference
`%ChocolateyToolsLocation%\` or `C:\Tools`

**Comment by bcurran3** [comment]
(Without looking...) I'm sure you're right. The GH files are not up to date with my local versions. I have conflicts and effups that I don't know how to easily fix. 

I'm going to leave this open until such time as I get my GitHub house in order and see if it needs to be addressed then.

I really need to figure out a solid workflow solution for Chocolatey packages...

**Comment by CodeCharm** [comment]
Would a GH action help, like this one? https://github.com/crazy-max/ghaction-chocolatey

**Comment by bcurran3** [comment]
@jeff9315 - I looked through all the CPLB files and can't find that string. I'm guessing it was removed when CPLB go the -EditConfig option back in:
* 2019.08.27 - can now put title and summary info into the packages.config file, new -EditConfig parameter to edit the config file, Now works from Command Prompt as well as PowerShell, script installation endpoint changed, config file renamed from .xml to .config

That's the release that the files got moved from chocolatey\bin to $env:ChocolateyToolsLocation\BCURRAN3.

Which is weird because that's 9 months before you brought up the issue!

----------------------------------

@CodeCharm - I looked at that and the purpose and instructions are non-existent. Can't figure out what it does except run a package in a container. I must have missed something. Feel free to explain more if you think it can help.
