### ISSUE TITLE
[intel-graphics-driver] Not updated anymore?

### ISSUE THREAD

**Issue by TheJanzap** [bcurran3/ChocolateyPackages_CCR#165]
I just wanted to ask why the intel-graphics-driver package isn't updated anymore, especially with the latest versions removing the check for OEM drivers.

https://downloadcenter.intel.com/download/29557/Intel-Graphics-Windows-10-DCH-Drivers?product=80939

**Comment by bcurran3** [comment]
Intel kept changing the installer every other version or so. (If I remember correctly) one would be a zip, next would be an .exe, and the autohotkey script became a nightmare to keep re-doing. After spending multiple hours on two or three releases and not having a working package, I shelved it. I'll dig it up and look into it again sometime in the near future.

**Comment by bcurran3** [comment]
On top of that when the DCH drivers first came out, the would be on the website for a few days and then disappear. REALLY DISCOURAGING! 

The new version you linked too seems to support a silent install. (Technically silent install was an option before but it technically didn't work since it would still run and pop up their experience feedback program which required AHK to get around.) Let's hope they stick to a consistent format for the future.

I just pushed an updated package for you. Testing the install program with /S worked for me, but after packaging it up and trying to install it, I get a -2147024889 error. No clue what it means but hoping it simply means that the drivers are already installed.

Give this a shot and let me know if it works for you. If it does, run it again with -f to force and let me know if you get that -2147024889 error as well. TIA.

`cup intel-graphics-driver --version 27.20.100.8190`

**Comment by bcurran3** [comment]
UPDATE: I just ran it on identical hardware and received the same error message so something else is going on. I'll look into it more later.

**Comment by TheJanzap** [comment]
I've also tried it with the command you provided above and also recieved a -2147024889 exit code with and without `--force`. Sadly it doesn't seem to install the drivers either, as Device Manager still reports the driver I had previously installed

**Comment by TheJanzap** [comment]
The installer drops a log file under `%localappdata%\Temp\chocolatey` and it seems like it fails to launch the exe after the installer has unpacked all the necessary files (for whatever reason):

> [0510:1424][2020-06-01T12:55:14]i301: Applying execute package: SetupExe, action: Install, path: C:\ProgramData\Package Cache\D787A54659376D2FA6E4EB0B541C39D8186BDD1C\igxpin.exe, arguments: '"C:\ProgramData\Package Cache\D787A54659376D2FA6E4EB0B541C39D8186BDD1C\igxpin.exe" -s'
[0510:1424][2020-06-01T12:55:17]e000: Error 0x80070007: Process returned error: 0x7
[0510:1424][2020-06-01T12:55:17]e000: Error 0x80070007: Failed to execute EXE package.
[0578:381C][2020-06-01T12:55:17]e000: Error 0x80070007: Failed to configure per-machine EXE package.
[0578:381C][2020-06-01T12:55:17]i319: Applied execute package: SetupExe, result: 0x80070007, restart: None
[0578:381C][2020-06-01T12:55:17]e000: Error 0x80070007: Failed to execute EXE package.

**Comment by bcurran3** [comment]
Thanks for helping.

I discovered even though the installer says /S someplace for silent install, the underlying igfx program needs -s. So I repackaged using that <s>and It worked on the machine which already had the drivers</s> and failed with the same error on the machine with out of date drivers. Did some digging into the logs and discovered:
```
  4ID Check Failed.  Removed INF = C:\ProgramData\Package Cache\D787A54659376D2FA6E4EB0B541C39D8186BDD1C\Graphics\iigd_dch.inf
!   Installed driver uses 4IDs and installing driver uses less. Get driver from manufacturer website.
```
I deleted the installed drivers and then the package failed since I check for Intel video. :) Removed that from the  checking from the scripts and got a -2147024891 again. UGH!

I'm going to play more later. I plan to manually install drivers that are one or two versions out of date, then update to current via the package and see what happens.

**Comment by TheJanzap** [comment]
I tried it again to upgrade from version 26.20.100.8141 to the one in the package. The installer ran and also seemed to install the drivers. But a look in the Device Manager showed that the drivers were actually downgraded to 26.20.100.7584 (what?!?).

The installer seemed stuck as well, with choco displaying that it is still installing, but I couldn't find a process that corresponded to the installer.

Event viewer also revealed that dwm.exe, TextInputHost.exe and StartMenuExperienceHost.exe crashed, so I don't know what in the world the installer is doing.

**Comment by bcurran3** [comment]
More examples of the weird stuff for Intel installs....

There is a ZIP that has the igxpin.exe installer in it. I'll probably try that instead of the installer that's wrapped around it.

BTW: someone in the release notes/docs it says you need to reboot to finish installing the software. I'm guessing the drivers don't need it, but things change and maybe you do now.

**Comment by ghost** [comment]
On my Acer Predator Triton 500, I think 2 out of the 5 Intel driver installs want a reboot, I'll test it now. Plz hold.

**Comment by ghost** [comment]
https://i.imgur.com/oP5447U.jpg

It wants a restart. Again, this is for an Acer Predator Triton 500, and this comes from their product support page. Lmk if you want anything else from my end. I'm new to the scene, but I'm going to try to make this a package and Logitech G-Hub. I'll circle back with you @bcurran3 in a few days Sir. 🙇‍♂️

**Comment by bcurran3** [comment]
Irony is a new version came out a day or two ago...

**Comment by bcurran3** [comment]
> https://i.imgur.com/oP5447U.jpg
> 
> It wants a restart. Again, this is for an Acer Predator Triton 500, and this comes from their product support page. Lmk if you want anything else from my end. I'm new to the scene, but I'm going to try to make this a package and Logitech G-Hub. I'll circle back with you @bcurran3 in a few days Sir. 🙇‍♂️

If I have the AHK script right (bane of my existence), you won't get the prompt.

**Comment by ghost** [comment]
Can you hit me up when this is live Sensei? (¬‿¬)

Edit: Done tag is set on this issue, does that mean the work is completed, but the package needs to pass PR on Chocolatey's end? Tried to pull down, URL is still ethered.

**Comment by PissedCapslock** [comment]
Not sure if it is relevant for this issue, but I could not install this package because my Windows10 did not had the necessary updates.
So I installed the latest Intell driver (27.20.100.8336) directly using the following puppet code (I'm using puppet in combination with chocolatey):

```
    exec{'install_intel_driver':
      command => 'Start-Process -FilePath "V:\\igfx_win10_100.8336.exe" -ArgumentList "-overwrite","-s" -Wait',
      onlyif  => 'if(Get-WmiObject Win32_PnpSignedDriver | Where-Object {$_.DeviceName -Like "Intel*Graphics*" -And $_.DriverVersion -eq "27.20.100.8336"}){ exit 1 }',
     provider => powershell
    }
```

With the new silent installation option, it becomes rather trivial and might greatly simplify the code behind this package.

**Comment by bcurran3** [comment]
You guys get some joy today:
https://chocolatey.org/packages/intel-graphics-driver/27.20.100.8190
