### ISSUE TITLE
Chocolatey Preinstaller Checks Extension: All tasks are paused waiting for each other, eventually "multiple package installation at same time" does not work

### ISSUE THREAD

**Issue by ghost** [bcurran3/ChocolateyPackages_CCR#211]
You can see here all tasks are paused waiting for each other for infinite time, so i m forced to run 1 task at a time because multiple packages installation at same time does not work, please resolve this issue

![image](https://user-images.githubusercontent.com/58593523/96637237-dace1500-1337-11eb-8d66-ee6725c364dd.png)

![image](https://user-images.githubusercontent.com/58593523/96637277-e7eb0400-1337-11eb-99e7-81cb8a1c6393.png)

**Comment by ghost** [comment]
same issue I also mentioned here https://github.com/BananaAcid/chocolatey-appstore/issues/1 , but its actually this package issue, not issue of extention

**Comment by bcurran3** [comment]
@umarabdullahmansoori this has nothing to do with choco-protocol-support and everything to do with chocolatey-preinstaller-checks.extension. Take a look at the instructions for that and edit your AbortSeconds value in the XML file. 

chocolatey-preinstaller-checks.extension was never intended to be used this way. I love the idea you have of trying it this way though. chocolatey-preinstaller-checks.extension was built with the idea that you might run a choco command when another one was running without your knowledge; i.e. a scheduled task that you forgot about or didn't realize the time. It handles a 2nd copy of choco running but goes into a loop when there are three or more and doesn't know how to get out of it. Not doom and gloom though, that's what the abort time out is for that I mentioned above. 

Now with all that said.... I don't think I ever implemented the abort time out! HAHAHHA For a next version that hasn't come yet. I think you want to look at your AbortOnMultiples setting (default false) and change it to true and then you won't get the situation you experienced because it's designed to stop that from happening... basically you won't be able to queue up these installs like you want. 

packages.config file is designed to do what you want to do.

**Comment by ghost** [comment]
> @umarabdullahmansoori this has nothing to do with choco-protocol-support and everything to do with chocolatey-preinstaller-checks.extension. Take a look at the instructions for that and edit your AbortSeconds value in the XML file.
> 
> chocolatey-preinstaller-checks.extension was never intended to be used this way. I love the idea you have of trying it this way though. chocolatey-preinstaller-checks.extension was built with the idea that you might run a choco command when another one was running without your knowledge; i.e. a scheduled task that you forgot about or didn't realize the time. It handles a 2nd copy of choco running but goes into a loop when there are three or more and doesn't know how to get out of it. Not doom and gloom though, that's what the abort time out is for that I mentioned above.
> 
> Now with all that said.... I don't think I ever implemented the abort time out! HAHAHHA For a next version that hasn't come yet. I think you want to look at your AbortOnMultiples setting (default false) and change it to true and then you won't get the situation you experienced because it's designed to stop that from happening... basically you won't be able to queue up these installs like you want.
> 
> packages.config file is designed to do what you want to do.

Thank you for reply, 
My problem is solved after uninstalling CHOCOLATEY PREINSTALLER CHECKS EXTENSION
It was stopping chocolatey from installing multiple packages
( https://chocolatey.org/packages/chocolatey-preinstaller-checks.extension )
