### ISSUE TITLE
Choco Cleaner - Final Wait Step

### ISSUE THREAD

**Issue by hl2guide** [bcurran3/ChocolateyPackages_CCR#240]
Please consider adding a config setting for setting the number seconds for the final delay in the script.

e.g. the very last

`Start-Sleep`

**Comment by bcurran3** [comment]
Dean,

It's purposeful to see the "beg screen" when run from the GUI. :) 
You're welcome to just delete the line yourself.

**Comment by bcurran3** [comment]
Thinking back, that was added so that you had time to read the results when run from the Start Menu icon.

Theoretically, if I could determine if the script was run from the Command Prompt as opposed to the GUI, I could skip the delay as there would not be a need.

I VAGUELY remember looking into if it was possible to determine between the two. Not sure it was related to this or not. If you find a reference to do this, I'm willing to implement.

**Comment by bcurran3** [comment]
I'm going to re-open this.

Need to read and test based on:
https://stackoverflow.com/questions/9419875/determining-if-batch-script-has-been-started-executed-from-the-command-line-cmd
and
https://serverfault.com/questions/866281/determine-if-powershell-script-has-been-run-from-the-desktop-or-command-line

**Comment by bcurran3** [comment]
I looked into this and tried to implement before pushing a the new v0.0.8.1 of Choco-Cleaner. Unfortunately the "solutions" I looked into didn't work. They were either outdated or too clunky.  

If you can find a working way to check if the script was run from CLI or GUI, I'll be glad to re-open and revisit. 

Keep in mind that this may not even be possible since Choco-Cleaner is going to usually be executed via choco-cleaner.bat which calls PowerShell and the script. So I assume it would always "think" it's run from the command line and negate the purpose of the delay to see the results when run from the GUI.
