### ISSUE TITLE
[choco-cleaner] Thousands separator appears in freed space negativity check

### ISSUE THREAD

**Issue by kitlei-robert** [bcurran3/ChocolateyPackages_CCR#244]
You should use `'D'` as the [format specifier](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings) on [this line](https://github.com/bcurran3/ChocolateyPackages/blob/master/choco-cleaner/tools/choco-cleaner.ps1#L297) instead of `'N0'`, as currently `$FreedSpace` can be set to values such as `"615 376"` which cannot be converted to an int:

`Cannot convert value "615 376" to type "System.Int32". Error: "Input string was not in a correct format."`

**Comment by bcurran3** [comment]
Hey @kitlei-robert,

Thanks for the quick feedback.

I'm trying to figure out how the hell a space got in your FreedSpace variable! Maybe I need to make sure all the free space variables are declared as integers and this won't happen because when I test with either formatter I get errors:
![image](https://user-images.githubusercontent.com/14026600/111087378-83933180-84de-11eb-855a-e00274a9c6ac.png)

Thoughts?

**Comment by kitlei-robert** [comment]
`$FreedSpace` is a proper int that's getting converted to a string, and then the [check on the next line](https://github.com/bcurran3/ChocolateyPackages/blob/master/choco-cleaner/tools/choco-cleaner.ps1#L298) complains about an invalid conversion (back to an int).

```
PS C:\Users\user> $test="615 376"
PS C:\Users\user> $test.ToString('N0')
Cannot find an overload for "ToString" and the argument count: "1".
At line:1 char:1
+ $test.ToString('N0')
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest

PS C:\Users\user> $test=615376
PS C:\Users\user> $test.ToString('N0')
615 376
PS C:\Users\user> $test.ToString('D')
615376
```

**Comment by bcurran3** [comment]
I'm getting a different result with a comma instead of a space.
Could this be a PS version issue? What ver are you running?

![image](https://user-images.githubusercontent.com/14026600/111091355-e3de9f00-84ef-11eb-9885-dffef0b5a95e.png)

Just tried with Core and got the same result:
![image](https://user-images.githubusercontent.com/14026600/111091386-01ac0400-84f0-11eb-9673-5e6a902633bf.png)

**Comment by bcurran3** [comment]
UPDATE:

I do see 'D' returns without the comma:
![image](https://user-images.githubusercontent.com/14026600/111091479-4f287100-84f0-11eb-8499-0c69b62131b1.png)
![image](https://user-images.githubusercontent.com/14026600/111091491-5485bb80-84f0-11eb-818e-cd1b9cb94f5b.png)

Still trying to figure out why this isn't working out
![image](https://user-images.githubusercontent.com/14026600/111091623-c5c56e80-84f0-11eb-8001-db7cde08d47d.png)


Might be easier to just do if freebefore > freeafter than 0

Will work on more later.

**Comment by kitlei-robert** [comment]
It is `5.1.19041.610`, but that's irrelevant. See this:

```
PS C:\Users\user> Get-Culture

LCID             Name             DisplayName
----             ----             -----------
1038             hu-HU            Hungarian (Hungary)
```

With `en-US`, it gives me the comma, too.

I agree that using the number(s) in the comparison is clearer.

**Comment by bcurran3** [comment]
Bingo!

This works if ($freedspace -match '-') {write-host negative} - I can check for negative numbers this way and then apply appropriately. Going to go implement now.

EDIT: I was distracted by someone and got off track - I'll go fix the relevant part now.

Thanks for bringing up this interesting bug!

**Comment by bcurran3** [comment]
Could you edit your script to this below and see how it works?


move  
`if ([double]$FreedSpace -lt 0) {$FreedSpace = "0"} `
above 
`$FreedSpace = $FreedSpace.ToString('N0')`
note I changed int to double


```

**Comment by Wowbagger15** [comment]
Hi Bill,

Stepping in with the same issue. The problem is that the 'N' format specifier uses the system locale's thousand separator. If set to nil then of course conversion has no issues but if people (or a location's common practice) set it to for example a dot or a comma, then conversion to an integer obviously fails. https://ss64.com/ps/syntax-f-operator.html states (note the second part of the remark):

:n | Number (:nP precision=number of decimal places), includes culture separator for thousands 1,000.00

Either the format specifier 'f' should be used with a precision of 0, so 'f0' or no conversion at all until the final display. I personally *never* convert anything numeric until I need it displayed and then (try to) rely solely on the formatting features of the scripting/programming language at hand.

The conversion to a double is unnecessary because the division will already take care of that:

PS > ( $FreedSpace / 1024 ).gettype().name
Double

Suggestion for lines 312..318 :

$freedSpace = [int64]( ( ( get-item $env:chocolateyInstall ).PSdrive.free - $freeBefore ) / 1024 );

cheers, Bob

**Comment by bcurran3** [comment]
Thanks. I appreciate the help.

For whatever reason I still can't wrap my head around where the problem is. I guess I should have asked for the PS error (with line number and pointing to the problem) to understand better.

@Wowbagger15 - I think by lines 312...318 you mean lines 295...297?

Where I THINK I understand the problem is :      $FreedSpace = $FreedSpace.ToString('N0')

What I THINK a solution is: Remove that line.

The intent of that line is to convert the number to a string with thousands separation. 

I THOUGHT the string conversion would handle culture, but I guess not. Or I'm looking at the wrong problem or wrong place?

If I'm on track, how do I get $Freedspace to print with Write-Host using the correct culture thousands separator.

**Comment by Wowbagger15** [comment]
Hello Bill,

Sorry, line numbers mismatch because I've inserted an altered version of the Test-ShimTargetExists function, other issue ;-) . I meant **294**..297 , yes, Note one line before is wrapped up in the suggestion as well!

The problem is doing math having converted to a string that is not guaranteed to convert back to a number. By postponing formatting this all goes away and output tasks are done where due.

So yes, remove that line. In fact, I'd wrap up the computation as suggested earlier in a single line and follow it up with output (replacing lines 298..304) like this:


    if ( $freedSpace ) {
        '{0} Choco-Cleaner FINISHED deleting unnecessary Chocolatey files and reclaimed ~ {1:N0} kB !' -f ( get-date ), $freedSpace | tee -append "$ENV:ChocolateyToolsLocation\BCURRAN3\choco-cleaner.log" | write-host -foreGround magenta;
    } else {
        '{0} Choco-Cleaner FINISHED deleting unnecessary Chocolatey files!' -f ( get-date ) | tee -append "$ENV:ChocolateyToolsLocation\BCURRAN3\choco-cleaner.log" | write-host -foreGround magenta;
    }


On my system, this looks like (imaginary value of course ;-)

`20210326 13:40:36 Choco-Cleaner finished deleting unnecessary Chocolatey files and reclaimed ~ 568.567.576 kB !`


cheers, Bob

Edit: Made a typo in the format parameters effectively switching date and bytes ^_^

**Comment by salsifis** [comment]
Hello, the merge request submitted today fixes this problem.

**Comment by bcurran3** [comment]
This just got this fixed and merged in. Thanks salsifis!
https://github.com/bcurran3/ChocolateyPackages/pull/255
(Choco-Cleaner.ps1 v0.0.8.3 (05/10/2021))
