### ISSUE TITLE
(choco-package-list-backup) slow to run with chocolatey licensed and lots of packages.

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [bcurran3/ChocolateyPackages_CCR#249]
With over 200 packages installed and using Chocolatey professional, it takes about 90 seconds to run choco-package-list-backup.ps1 when saving to two locations total. (not including the time for start-sleep at the end)

The main reason for this is that installing `chocolatey.extension` is like installing `chocolatey-molasses-mode`. Running `choco list -lo` takes five seconds, instead perhaps two with FOSS chocolatey.

My main thought for fixing this is instead of re-creating the `.config` xml data every time `Write-PackagesConfig` is run, it could be gotten once, then output to each location as needed.

**Comment by bcurran3** [comment]
Yeah, the re-creating the same data over and over is definitely not optimal. I've thought about this in the past too, to basically create it once in a first/default location (thinking now that Public might be best) and then copy it to the other configured destinations. Since I rely on CPLB to be created automatically in the wee hours of the night, this has been low priority for me... but unofficially on the roadmap.

Thanks for bringing this back to my attention. 
(Or is that darn you for making me lose more sleep some night soon?).

**Comment by TheCakeIsNaOH** [comment]
> I've thought about this in the past too, to basically create it once in a first/default location (thinking now that Public might be best) and then copy it to the other configured destinations.

Since it's not a gigantic amount of data, I was thinking of storing it in a variable, then doing `out-file` as needed. 

> (Or is that darn you for making me lose more sleep some night soon?).

🤣 

I'm perfectly happy to work on this, I just want to get #235 out of the way first, since these touch the same areas.

**Comment by bcurran3** [comment]
That sounds like an even better idea to me!

**Comment by bcurran3** [comment]
I'm going to go pull in https://github.com/bcurran3/ChocolateyPackages/pull/235 now.

**Comment by bcurran3** [comment]
Thanks TheCakeIsNaOH!
