### ISSUE TITLE
#Requires -RunAsAdministrator line

### ISSUE THREAD

**Issue by master-nemo** [bcurran3/ChocolateyPackages_CCR#279]
Sorry if it repeats or my local error.

When I tried to run choco-cleaner.bat i had an error: 

``` 
C:\tools\BCURRAN3\choco-cleaner.ps1:2 знак:11
+ #Requires -RunAsAdministrator
+           ~~~~~~~~~~~~~~~~~~~
Для параметра RunAsAdministrator требуется аргумент.
	+ CategoryInfo          : ParserError: (:) [], ParseException
	+ FullyQualifiedErrorId : ParameterRequiresArgument

```
sorry for the Russian error description. It means `require argument for parameter RunAsAdministrator `.
So I looked at choco-cleaner.ps1 and noticed `#Requires -RunAsAdministrator`. So I just added space after #: `# Requires -RunAsAdministrator` and that error was disappeared.  

thank you for your useful tool
...
```
my OS: win7sp1
PowerShell version: 3.0
```

**Comment by bcurran3** [comment]
Hi. That's by design and a feature. For CC to clean everything it needs admin rights to some directories such as where Chocolatey is installed. So you should run Command Prompt or PowerShell as Administrator and 1> you won't get that error 2> It'll clean all it's supposed to clean.

пожалуйста - Glad you like it and find it useful.

**Comment by master-nemo** [comment]
yes, I understand that it must be run as an administrator.
Yes, I started it from the console, which was run as administrator. 
And it works (but only when space was added). And fail (as administrator!) when no space.
