### ISSUE TITLE
[Choco Package List Backup] Reinstalling config file overwrite pins.bat

### ISSUE THREAD

**Issue by Bazzu85** [bcurran3/ChocolateyPackages_CCR#285]
Hi, 
today I reinstalled the system and used the CIST command to reinstall the backup config from OneDrive folder.

The first problem I found is that after the installation, the pins.bat vanished.
The other problem is that during the installation, after the CPLB reinstallation, the script is launched overwriting all (including pins.bat)

any feedback?

**Comment by bcurran3** [comment]
Hi @Bazzu85. Thanks for commenting.

All pretty much expected behavior. CPLB can be run with the /NORUN:TRUE option which would install it without running CPLB during install. I know, it's a 20/20 hindsight thing now.

If you have AppendDate set to true in the config you'll have further backup copies of packages.config and pins.bat. Chocolatey parses the whole packages.config file so no harm done there overwriting a new one with the same data (presuming no failures) but I can see how the pins.bat being overwritten can be minorly annoying. I don't see an automated way to get around this. The solution really comes down to using the /NORUN:TRUE option, moving the packages.config and pins.bat out of one of the default landing zones, or using a pins_YYYY-MM-DD.bat file (created by the AppendDate set to true) to restore pins after re-installing packages. 

**I'm going to leave this open and probably introduce a simple packages.bak and pins.bak file for situations when the AppendDate feature is not active.**

**Comment by Bazzu85** [comment]
> Hi @Bazzu85. Thanks for commenting.
> 
> All pretty much expected behavior. CPLB can be run with the /NORUN:TRUE option which would install it without running CPLB during install. I know, it's a 20/20 hindsight thing now.
> 
> If you have AppendDate set to true in the config you'll have further backup copies of packages.config and pins.bat. Chocolatey parses the whole packages.config file so no harm done there overwriting a new one with the same data (presuming no failures) but I can see how the pins.bat being overwritten can be minorly annoying. I don't see an automated way to get around this. The solution really comes down to using the /NORUN:TRUE option, moving the packages.config and pins.bat out of one of the default landing zones, or using a pins_YYYY-MM-DD.bat file (created by the AppendDate set to true) to restore pins after re-installing packages.
> 
> **I'm going to leave this open and probably introduce a simple packages.bak and pins.bak file for situations when the AppendDate feature is not active.**

Thx for quick reply.
To be more specific for me and future readers...
when running `cinst packages.config -y`, all the content is installed automatically.
You mean that I have to modify the `packages.config` to add the `/NORUN:TRUE` option?

BTW the `.bak` file is a good solution. I now added the `AppendDate` options..

I would like some advice about reinstalling..
usually I install chocolatey from site command line. After that I go to the folder and launche the `cinst packages.config -y`.
is this the correct and quickisest way?
additionally (sorry for adding things) a couple of things..
- I see that in google drive (ex Filestream) CPLB doesn't save to a ChocolateyPackageListBackup folder (is enabled in options)
- the document folder saving is not splitted by machine. this is a problem with shared document folder across devices..

**Comment by bcurran3** [comment]
I added backups to the backups today:
* 2022.02.06 - All existing files now renamed with .bak before creating new versions. This backup is useful during migrations where the files could get overwritten during install of CPLB on a new computer. (https://github.com/bcurran3/ChocolateyPackages/issues/285)

**Comment by bcurran3** [comment]
@Bazzu85 To respond to your questions and comments:

> You mean that I have to modify the packages.config to add the /NORUN:TRUE option?

Yes, but not easy to do when re-installing. Until this update, it would probably have been easier to delete CPLB from the packages.config and then install manually - it really should be the last thing you install so that it captures all your packages. The first iteration of results is not really useful after install on a new machine and really needs to be run manually once afterwards (or wait until it's scheduled run) to have relevant results. 

This would be be handled if CPLB put itself at the bottom of the packages.config file. Something I should consider for the future; it's just going to be a PITA to do. 

> BTW the .bak file is a good solution. I now added the AppendDate options..

Good choice. Solves your original problem also the history can be useful under the rare occasion Chocolatey aborts an upgrade and looses management of the package.

> usually I install chocolatey from site command line. After that I go to the folder and launche the cinst packages.config -y.
> is this the correct and quickisest way?

Yup. Sounds good. Though you should look into InstChoco. :)

> I see that in google drive (ex Filestream) CPLB doesn't save to a ChocolateyPackageListBackup folder (is enabled in options)

GoogleDrive and GoogleFS keep changing and I haven't kept up with it. You could open a new issue and explain what is and isn't happening and I can look into it. As a general rule CPLB only checks the default paths the various cloud drive programs put their files.

> the document folder saving is not splitted by machine. this is a problem with shared document folder across devices..

C:\Users\username\Documents\ChocolateyPackageListBackup is only local. Thus only relevant to the local machine and can't be confused with any other machines. Because of this the files are purposely not put into a machine name subfolder. There's no need for that folder to distinguish between multiple machines when there's only ever going to be the info for one computer in there.
