### ISSUE TITLE
Plexamp 4.8.2 Fails to Install

### ISSUE THREAD

**Issue by xcjs** [bcurran3/ChocolateyPackages_CCR#344]
When running choco upgrade plexamp, I'm currently getting the following error:

```
plexamp v4.8.2 [Approved]
plexamp package files upgrade completed. Performing other installation steps.
Installing 64-bit plexamp...
WARNING: May not be able to find 'C:\ProgramData\chocolatey\lib\plexamp\tools\Plexamp Setup 4.8.2.exe'. Please use full path for executables.
ERROR: Exception calling "Start" with "0" argument(s): "The system cannot find the file specified"
The upgrade of plexamp was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\plexamp\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - plexamp (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\plexamp\tools\chocolateyinstall.ps1'.
 ```
 
 When I checked `C:\ProgramData\chocolatey\lib\plexamp\tools` for the Plexamp installer, I could not find it.

**Comment by bcurran3** [comment]
If you look at the files section of https://community.chocolatey.org/packages/plexamp/4.8.2 you'll see that Plexamp Setup 4.8.2.exe is included in the package. 

The only thing that makes sense to me is that your AV might have interfered. Please check your AV logs and/or try again to install and see what happens.

**Comment by xcjs** [comment]
I'm just using Windows Defender and don't see any logs suggesting that it interfered.

I've been installing Plexamp through an Ansible playbook that I manage, and while something strange could have happened on my end, it has worked for over a year until the most recent release. I can verify that the same issue occurs on all three of my Windows hosts.

I still use over 130 other Chocolatey packages without issue. Are you using a new Chocolatey feature that's not commonly used yet?

**Comment by bcurran3** [comment]
Ansible shouldn't be an issue.

If you're upgrading from 4.8.0 to 4.8.2, the install script is exactly the same.

Package hasn't changed since 4.7.3. (v4.7.3 started using   packageName    = "$env:ChocolateyPackageName" instead of packageName    = 'plexamp') - everything else is the same) 

Are you using an old version of choco that maybe doesn't have the $env:ChocolateyPackageName variable supported?

Nothing in the package requires any special features.

I just did an upgrade -f and it worked perfectly fine. 

You shouldn't be looking for the exe in libs\plexamp if it failed install, you should be looking at lib-bad\plexamp but the difference is moot since the package deletes the exe after (attempting) install.

-------------------------


`WARNING: May not be able to find 'C:\ProgramData\chocolatey\lib\plexamp\tools\Plexamp Setup 4.8.2.exe'. Please use full path for executables.`

Always funny when Chocolatey throws this error as it shows the full path to the file in the warning.

`ERROR: Exception calling "Start" with "0" argument(s): "The system cannot find the file specified"`

This is the real problem, it can't find the file. Usually when this happens either the file wasn't put into the package (it was) or AV interfered.

**Comment by xcjs** [comment]
I'll do some investigation this week and see how I managed to mess this up. 😅

I'll update the issue if I figure anything out. Thanks for getting back to me!

**Comment by bcurran3** [comment]
Ha!
Thanks.
I'll await your findings. Speak up if there are any Q's.

**Comment by xcjs** [comment]
@bcurran3 I was indeed using an ancient version of Chocolatey! I had assumed the win_chocolatey module in Ansible installed a recent version of Ansible (either that or its been so long since I've had to install Chocolatey since I usually have Ansible manage it for me) that I was still on version 0.2.2!

I'll be closing this issue and letting you get on with your life. Thanks for getting back to me!
