### ISSUE TITLE
choco-package-info-collection - Aggressive word wrapping

### ISSUE THREAD

**Issue by brogers5** [bcurran3/ChocolateyPackages_CCR#350]
I'm experiencing some usability and readability issues with `choco-package-info-releasenotes.hook`, but I see the other hooks in its collection have a similar implementation, and theoretically could have similar problems.

I've noticed the hook is hard-coded to format the relevant Nuspec string at a 5-space indentation, with 75 columns per line.

Some packages may have a long `releaseNotes` URL that exceeds this length (for example, one of my own packages: [xsplit-broadcaster](https://community.chocolatey.org/packages/xsplit-broadcaster/4.5.2307.2506)):

![Screenshot of long URL being wrapped](https://github.com/bcurran3/ChocolateyPackages/assets/6869577/29c7fd61-d466-4b51-9eb6-1ab2378bcf60)

The current behavior of splitting the URL to a separate line breaks Windows Terminal's URL detection feature by truncating the detected URL value, which could cripple the utility of the hook for such packages.

Some packages use a markdown string (for example: [gh](https://community.chocolatey.org/packages/gh/2.37.0)), which also doesn't play nicely with removed newlines:
![Screenshot of markdown release notes](https://github.com/bcurran3/ChocolateyPackages/assets/6869577/fdfeb872-99c0-4b6a-92f6-97223f630ac5)

Could you add an option to disable the word wrapping behavior and return the string as-is (to defer word-wrapping and other formatting decisions to the terminal emulator), or at least define a custom line-length value (possibly defaulting to [the current console width](https://devblogs.microsoft.com/scripting/powertip-determine-size-of-powershell-console/) minus the indentation width)?

**Comment by bcurran3** [comment]
First let me state I'm happy that someone found this hook of worth and is using it. Yay!

Second I'll state that this hook is minor and it's scope of work and functionality is to simply display some additional info and keep that info separated from Chocolatey's normal output as to standout and not get "lost in the noise" by using color and formatting. The formatting is intentional and the output is to be informative and not a meant to be multimedia slide presentation. :-) 80 character max length was chosen for backwards compatibility.

Thank you very much for the WindowSize variables; those will prove to be very useful and I'll plan to implement when I have a chance. <s>I use and LOVE Terminal, but I'll have to test if those variables are compatible with a non-Terminal PowerShell CLI window as well.</s> EDIT: $Host.UI.RawUI.WindowSize.Width and $Host.UI.RawUI.WindowSize.Height work fine in "normal" PowerShell window, so they are full on green light for me to redo the default line length formatting in an update.

**Comment by bcurran3** [comment]
Closing this as I am no longer creating or maintaining Chocolatey packages. Sorry, out
of my control.

Hopefully you've enjoyed my work and found it useful.

[![Bella Ciao!](https://img.youtube.com/vi/9ao4FEaDGhQ/0.jpg)](https://www.youtube.com/watch?v=9ao4FEaDGhQ)

**Comment by brogers5** [comment]
Thank you for your contributions to the Chocolatey community. I've found several of your packages to be useful over the years, and you will surely be missed.

On a related note, is your account on the Community Repository still active? [Your profile page](https://community.chocolatey.org/profiles/bcurran3) appears to be 404ing now:

![Page not found screenshot](https://github.com/bcurran3/ChocolateyPackages/assets/6869577/a803238a-4f49-4b49-a966-9494da86be2d)

I ask as I'm interested in taking over maintenance for this (and other packages), and am wondering if I need to step through the Package Triage process or if you could just add me as a maintainer directly.

**Comment by bcurran3** [comment]
Thanks for the kind words and I'm very happy you have gotten use from my little utilities.

Unfortunately, my account is gone; not by choice. All my packages are up for grabs. I don't have the ability to deal them out but I'm sure one of the various Chocolatey package moderators will be happy to assign any to you.

**Comment by brogers5** [comment]
Understood, thank you for clarifying. I wish you the best of luck in your future endeavors!
