### ISSUE TITLE
(choco-package-list-backup) add saved package parameters to packages.config

### ISSUE THREAD

**Issue by ckulenkampff** [bcurran3/ChocolateyPackages_CCR#52]
It would be great if I could insert package parameters manually into the packages.config. When updating the `packages.config` file the backup script should retain the parameters as long as the package is still installed. The script could inform me about those parameters during the backup so I can verify their relevance.

This issue is similar to issue #7.

**Comment by bcurran3** [comment]
Just to verify:
* you are talking about choco-package-list-backup?
* you mean you want a modified packages.config to be read and have the modifications (package parameters) then added into the newly created packages.config file by choco-package-list-backup?

**Comment by ckulenkampff** [comment]
Yeah, my workflow would be like this:
1. Install new package with parameters (e.g. the app should not add context menu entries in the explorer).
2. Perform a package list backup.
3. Manually change the `package.config` so that the entry for the new app contains all parameters that I added during its installation.

... repeat for other new applications. The previously entered parameters should not be lost in the process. Maybe a log message informs me about the "merge of the package config file". It might be problematic if I backup the list to more than one store. In this case I would have to edit all stored `package.config`s.

When I setup a new workstation I can use the list to install all applications the way I want (without thousands of new context menu entries etc.).

It's basically a workaround for #7.

BTW Thank you very much for your work! It is really a warm feeling to know one can restore all applications with more or less one click - so comfortable. 😊

**Comment by bcurran3** [comment]
@ckulenkampff 

https://github.com/bcurran3/ChocolateyPackages/issues/7 looks viable now with the information provided by @heldgen. I plan to attempt the inline C code method mentioned as I believe I will get a lot of push-back from the Chocolatey Team if I include an executable that directly defeats their encryption method. (Probably will get push-back with it included inline in the PS script, but I think that's an easier fight to deal with).

I think capturing and storing the package parameters at package list backup time seems more productive. The suggested workaround seems difficult, cumbersome, and manually time consuming (Even if a separate script was created, it means running a 2nd script.).

Since your request is a "workaround for https://github.com/bcurran3/ChocolateyPackages/issues/7", is it safe to say we can close this issue and make the other one a "priority?"

**Comment by ckulenkampff** [comment]
@bcurran3 Yes, I totally agree! #7 is much nicer. Thank you!
