### ISSUE TITLE
(choco-package-list-backup) check for error messages when running clist.exe

### ISSUE THREAD

**Issue by mkevenaar** [bcurran3/ChocolateyPackages_CCR#67]
Hi Bill,

I just created a backup using your package. It seems there was some sort of lock (I think from ChocolateyGUI).

I got the following output in the file:
```
   <package id="" version="This is try 1/3. Retrying after 400 milliseconds." />
   <package id="" version=" Error converted to warning:" />
   <package id="" version=" Access to the path 'C:\ProgramData\chocolatey\config\chocolatey.config.104028.update' is denied." />
   <package id="" version="This is try 2/3. Retrying after 600 milliseconds." />
   <package id="" version=" Error converted to warning:" />
   <package id="" version=" Access to the path 'C:\ProgramData\chocolatey\config\chocolatey.config.104028.update' is denied." />
   <package id="" version="Maximum tries of 3 reached. Throwing error." />
```

I am using version choco-package-list-backup 2019.01.04

Maurice

**Comment by bcurran3** [comment]
Hi Maurice,

Sorry you had a problem. I just tested running a package list backup with ChocolateyGUI running and had no problem. I'm guessing you were actually installing or uninstalling a program with ChocolateyGUI at the time. Assuming so, this is actually a Chocolatey problem.

Since the script runs choco.exe it is HIGHLY advised that you DO NOT run any other instances of choco.exe (and evidently ChocolateyGUI).

I've actually created an extension to stop such conflicts, check it out:
https://chocolatey.org/packages/chocolatey-preinstaller-checks.extension

There is a lot of info and links related to the problem I think you just had on the package web page.

Please confirm that was the problem and close the issue if so.

**Comment by mkevenaar** [comment]
Hi Bill,

I agree that this might be a problem with choco itself, however I think that the script could filter those "error" lines as the packages.config file is not usable this way. You might even want to check if there is an error and wait a couple of seconds to try again. As there is a scheduled task created, this might happen during the automated backup.

I think the ChocolateyGUI was loading the packages / updates when this happened.

**Comment by bcurran3** [comment]
Definitely a choco.exe problem., BUT a little extra error checking could never hurt!
(If I don't get to it first, Chocolatey v1.0 should solve this problem, but I'm sure I'll get to it first.)

**Comment by bcurran3** [comment]
So I started brainstorming and figured out how to take care of this.

Instead of redirecting the choco list output directly to the file, I'll save it to a variable and then check that variable for the 3 or so error messages that will pop up if choco.exe is running elsewhere. 

I just haven't decided if I'm going to retry or abort at that point, leaning towards abort.

**Comment by bcurran3** [comment]
Done.

The error handling has not real world tested but should work. :) 
Even if not, CPLB is better and faster due to new file writing methods instigated by this.

https://chocolatey.org/packages/choco-package-list-backup/2019.01.31

I'd appreciate it if you could test by installing a few packages (ChocolateyGUI or command line) and run CPLB while they are installing or duplicate the actions you did before... and report back. TIA.

***
**Click here to [Patreon-ize](https://www.patreon.com/bcurran3) the package maintainer.**
***

**Comment by bcurran3** [comment]
Hey Maurice,

Completely unrelated to THIS issue...

I saw your https://github.com/chocolatey/package-validator/pull/184

...and noticed you're a maintainer of 80+ packages.

Check this out:
https://chocolatey.org/packages/choco-nuspec-checker

**Comment by mkevenaar** [comment]
Hi Bill, 

I have seen CNC, looks very nice, thanks for creating that!

Implementing CNC in my AppVeyor would be best, however it will only serve my packages. In te package-verifier, it will serve the community.

Once the new version is approved, I will try to reproduce what happend.

Maurice
