### ISSUE TITLE
choco-package-list-backup - Backup the config xml too

### ISSUE THREAD

**Issue by agnordby** [bcurran3/ChocolateyPackages_CCR#91]
Would be nice if the script could offer to backup its config xml file.

**Comment by bcurran3** [comment]
I think this is a good idea and am down for it.

**Comment by jeff9315** [comment]
I also posted this on the chocolatey packages page ... it's the same as this except I also think a copy of instchoco could be put in the same directory so that everything is in the same place when you reinstall Windows or put this on a new PC.

I had a thought as to what would make both Package List Backup and instchoco even better. In order for instchoco to work the best, a copy of both the choco-package-list-backup.xml file and the instchoco executable should be copied to the directories specified in the xml file so that we know where instchoco.exe is and instchoco could restore the xml file to the correct place and use it's parameters.

**Comment by bcurran3** [comment]
InstChoco is copied to the backup packages.config backup destination already when InstChoco is found/installed.

InstChoco doesn't have anything to do with the choco-package-list-backup.xml file, backing that up and restoring it would all be done in choco-package-list-backup.ps1. InstChoco just hitches a ride from choco-package-list-backup.ps1 when it (InstChoco) is installed.

**Comment by bcurran3** [comment]
I take that back. InstChoco could look for the xml file and copy it back. Gotcha. Right on. 

Open a separate issue for InstChoco please as this issue will be closed today. I just added the config backup.

___

Click here to [Patreon-ize](https://www.patreon.com/bcurran3) the package maintainer.
___
